### ISSUE TITLE
echo-server and echo-client bang without debugging messages

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#126]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salvestrini](https://github.com/salvestrini)**
_Monday Oct 21, 2013 at 12:11 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/123_

----

It could be probably related to #123 ...

1) ./install-from-scratch `pwd`/build-1
2) ./install-from-scratch `pwd`/build-2

francesco@ikira:~/Lavoro/Nextworks/Progetti/EU/FP7/IRATI/repo/irati$ ./build-2/bin/echo-server 
19413(1382357331)#concurrency (DBG): Lockable created successfully
[-role, server]
Exception in thread "main" java.lang.NoClassDefFoundError: eu/irati/librina/ApplicationProcessNamingInformation
        at rina.utils.apps.echo.Echo.<init>(Echo.java:16)
        at rina.utils.apps.echo.Main.main(Main.java:92)
Caused by: java.lang.ClassNotFoundException: eu.irati.librina.ApplicationProcessNamingInformation
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 2 more

francesco@ikira:~/Lavoro/Nextworks/Progetti/EU/FP7/IRATI/repo/irati$ ./build-1/bin/echo-server 
19540(1382357340)#concurrency (DBG): Lockable created successfully
[-role, server]
Exception in thread "main" java.lang.NoClassDefFoundError: eu/irati/librina/ApplicationProcessNamingInformation
        at rina.utils.apps.echo.Echo.<init>(Echo.java:16)
        at rina.utils.apps.echo.Main.main(Main.java:92)
Caused by: java.lang.ClassNotFoundException: eu.irati.librina.ApplicationProcessNamingInformation
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 2 more

francesco@ikira:~/Lavoro/Nextworks/Progetti/EU/FP7/IRATI/repo/irati$ ./build-1/bin/echo-client
21056(1382357461)#concurrency (DBG): Lockable created successfully
[-role, client, -sdusize, 100, -count, 30]
Exception in thread "main" java.lang.NoClassDefFoundError: eu/irati/librina/ApplicationProcessNamingInformation
        at rina.utils.apps.echo.Echo.<init>(Echo.java:16)
        at rina.utils.apps.echo.Main.main(Main.java:92)
Caused by: java.lang.ClassNotFoundException: eu.irati.librina.ApplicationProcessNamingInformation
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 2 more

francesco@ikira:~/Lavoro/Nextworks/Progetti/EU/FP7/IRATI/repo/irati$ ./build-2/bin/echo-client
21138(1382357467)#concurrency (DBG): Lockable created successfully
[-role, client, -sdusize, 100, -count, 30]
Exception in thread "main" java.lang.NoClassDefFoundError: eu/irati/librina/ApplicationProcessNamingInformation
        at rina.utils.apps.echo.Echo.<init>(Echo.java:16)
        at rina.utils.apps.echo.Main.main(Main.java:92)
Caused by: java.lang.ClassNotFoundException: eu.irati.librina.ApplicationProcessNamingInformation
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        ... 2 more

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Monday Oct 21, 2013 at 12:58 GMT_

----

Workaround:

1) cd rinad/src/application/rina.utils.apps.echo
2) mvn clean install

and try again

It happens sometimes, don't know why. The jar expects to see a version of librina that is different from the version copied in the /lib folder...
