### ISSUE TITLE
IPCM crashes when starting up on kernel 5.4

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#1360]
IPCM gets a segmentation fault and crashes while initializing IPC Processes (loading the policy set). Here is the GDB output:

````
Thread 1 "ipcm" received signal SIGSEGV, Segmentation fault.
0x00007ffff746f553 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007ffff746f553 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x0000555555581c98 in rinad::Catalog::plugin_loaded (this=this@entry=0x55555568d640, plugin_name="rina-default-plugin", ipcp_id=<optimized out>, ipcp_id@entry=4, load=load@entry=true)
    at /usr/include/c++/9/ext/new_allocator.h:89
#2  0x00005555555b141f in rinad::IPCManager_::plugin_load (this=this@entry=0x55555568d5e0, callee=callee@entry=0x0, promise=promise@entry=0x7fffffffb250, ipcp_id=ipcp_id@entry=4, 
    plugin_name="rina-default-plugin", load=load@entry=true) at /home/irati/stack/rinad/src/ipcm/ipcm.cc:1679
#3  0x0000555555606e9b in rinad::Catalog::load_policy_set (this=<optimized out>, addon=0x0, ipcp_id=4, ps_info=...) at //include/librina/patterns.h:68
#4  0x0000555555607646 in rinad::Catalog::load (this=this@entry=0x55555568d640, addon=addon@entry=0x0, ipcp_id=ipcp_id@entry=4, t=...) at /usr/include/c++/9/ext/aligned_buffer.h:72
#5  0x00005555555abc51 in rinad::IPCManager_::assign_to_dif (this=0x55555568d5e0, callee=0x0, promise=0x7fffffffceb0, ipcp_id=<optimized out>, dif_template=..., dif_name=...)
    at /home/irati/stack/rinad/src/ipcm/ipcm.cc:696
#6  0x00005555555aeafb in rinad::IPCManager_::apply_configuration (this=this@entry=0x55555568d5e0) at /home/irati/stack/rinad/src/ipcm/ipcm.cc:1171
#7  0x00005555556176cb in rinad::ScriptingEngine::ScriptingEngine (this=0x5555556aa110) at //include/librina/patterns.h:68
#8  0x0000555555589269 in rinad::Addon::factory (conf=..., name="scripting") at /home/irati/stack/rinad/src/ipcm/addon.cc:55
#9  0x00005555555a67df in rinad::IPCManager_::load_addons (this=0x55555568d5e0, addon_list=...) at /home/irati/stack/rinad/src/ipcm/ipcm.cc:197
#10 0x00005555555969d9 in wrapped_main (argc=5, argv=0x7fffffffe5b8) at //include/librina/patterns.h:68
#11 0x0000555555586861 in main (argc=5, argv=0x7fffffffe5b8) at /home/irati/stack/rinad/src/ipcm/main.cc:232
````

**Comment by edugrasa** [comment]
Fixed by commit to Master, should have created a different branch and merged, sorry for that!
