### ISSUE TITLE
Enrollment succeeds but allocation of management flow fails

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#270]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Jan 21, 2014 at 13:11 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/267_

----

Scenario:

node A: Runnning test1.IRATI (in normal.DIF) over shim eth
node B: Running test2.IRATI (in normal.DIF) over shim eth

Enrolling so they become neighbours gives the following message:

}2014-01-21 14:08:15,540 - DEBUG rina.ipcprocess.impl.flowallocator.FlowAllocatorInstanceImpl - The directory forwarding table returned address 0
}2014-01-21 14:08:15,541 - INFO rina.ipcmanager.impl.IPCManager - Got event of type: IPCM_ALLOCATE_FLOW_REQUEST_RESULT and sequence number: 1390309670
}2014-01-21 14:08:15,541 - INFO rina.ipcmanager.impl.helpers.FlowManager - Could not allocate flow from application Process name: test2.IRATI; Process instance: 1; Entity name: ; Entity instance:  to remote application Process name: test1.IRATI; Process instance: 1; Entity name: ; Entity instance:  in DIF Process name: normal.DIF; Process instance: ; Entity name: ; Entity instance: 
}2014-01-21 14:08:15,541 - INFO rina.ipcmanager.impl.helpers.FlowManager - Trying flow allocation again with IPC Process Process name: 15; Process instance: ; Entity name: ; Entity instance: 
}2014-01-21 14:08:15,553 - INFO rina.ipcmanager.impl.IPCManager - Got event of type: IPCM_ALLOCATE_FLOW_REQUEST_RESULT and sequence number: 1390309671
}2014-01-21 14:08:15,554 - ERROR rina.ipcmanager.impl.helpers.FlowManager - Problems processing IpcmAllocateFlowRequestResultEvent. Handle: 1390309671; Local application name: Process name: test2.IRATI; Process instance: 1; Entity name: ; Entity instance: ; Remote application name: Process name: test1.IRATI; Process instance: 1; Entity name: ; Entity instance: ; DIF name: Process name: normal.DIF; Process instance: ; Entity name: ; Entity instance: 
}2014-01-21 14:08:15,554 - INFO rina.ipcprocess.impl.IPCProcess - Got event of type: ALLOCATE_FLOW_REQUEST_RESULT_EVENT and sequence number: 1390309668
}2014-01-21 14:08:15,554 - ERROR rina.ipcprocess.impl.resourceallocator.flowmanager.NMinus1FlowManagerImpl - Allocation of N-1 flow denied. Error code -1
}2014-01-21 14:08:15,555 - INFO rina.ipcprocess.impl.ribdaemon.BaseRIBDaemon - Event N minus 1 Flow Allocation Failed has just happened. Notifying event listeners.
}2014-01-21 14:08:15,556 - WARN rina.ipcprocess.impl.enrollment.EnrollmentTaskImpl - The allocation of management flow identified by handle 1390309668 with the following charachteristics eu.irati.librina.FlowInformation@9ffe3f has failed. Error code: -1
}2014-01-21 14:09:03,497 - ERROR rina.ipcprocess.impl.ribdaemon.RIBDaemonImpl - Error decoding CDAP message: Receive a M_READ CDAP message on a CDAP session that is not open, over flow 2
}rina.cdap.api.CDAPException: Receive a M_READ CDAP message on a CDAP session that is not open, over flow 2
        at rina.cdap.impl.CDAPSessionManagerImpl.messageReceived(CDAPSessionManagerImpl.java:210)
        at rina.ipcprocess.impl.ribdaemon.RIBDaemonImpl.cdapMessageDelivered(RIBDaemonImpl.java:115)
        at rina.ipcprocess.impl.ribdaemon.ManagementSDUReader.run(ManagementSDUReader.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:679)

**Comment by kewinrausch** [comment]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lbergesio](https://github.com/lbergesio)**
_Thursday Jun 05, 2014 at 16:19 GMT_

----

To be closed
