### ISSUE TITLE
Error when closing ipcmanager console with an "exit"

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#329]
<a href="https://github.com/bernatgaston"><img src="https://avatars.githubusercontent.com/u/6225187?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bernatgaston](https://github.com/bernatgaston)**
_Tuesday Mar 11, 2014 at 15:05 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/326_

----

No kernel logued issues, seems userspace

}2014-03-11 15:20:53,949 - ERROR rina.ipcmanager.impl.console.IPCManagerConsole - Error closing socket: Socket is closed
}java.net.SocketException: Socket is closed
	at java.net.Socket.shutdownInput(Socket.java:1403)
	at rina.ipcmanager.impl.console.IPCManagerConsole.run(IPCManagerConsole.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:679)

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Jun 06, 2014 at 08:45 GMT_

----

This still happens. It's when you exit the ipcmanager console and the OS closes the socket before the ipcmanager can close it.

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Monday Oct 27, 2014 at 13:27 GMT_

----

Not reproducible since the IPC Manager has been ported to Java.
