### ISSUE TITLE
rina-echo-time: segfaulty Flow* access in Server::destroyFlow()

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#413]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Friday Oct 31, 2014 at 16:05 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/410_

----

If FLOW_DEALLOCATE_EVENT  comes before the timeout expires, the destroyFlow() function will try to access a Flow* pointer that has been freed by flowDeallocated(). This easily (always) happens in appovershim setup.

One can think that in order to solve this we could store in sigval_ptr the port-id associated to the flow instead of the Flow*. That would avoid invalid memory access, but could also mistakenly destroy another unrelated flow (maybe created by another application) that happens to have the same port-id, that was just freed by flowDeallocate().

So another solution is needed.

**Comment by kewinrausch** [comment]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmaffione](https://github.com/vmaffione)**
_Wednesday Nov 12, 2014 at 13:36 GMT_

----

This issue is not fixed as claimed in https://github.com/douwedb26/irati/commit/ec5fc42550b2090542c811be27d0c84971d4cc12, the timer can always fire before timer_delete() but after the flow has been destroyed (deallocated) by the event loop.

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Thursday Nov 27, 2014 at 16:18 GMT_

----

Seems related? There is still a segmentation fault when the flow is destroyed (output from gdb)

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb71ffb70 (LWP 6431)]
0xb7dac1cd in timer_delete () from /lib/i386-linux-gnu/i686/cmov/librt.so.1
(gdb) bt
#3  0xb7dac1cd in timer_delete () from /lib/i386-linux-gnu/i686/cmov/librt.so.1
#4  0x0804cde4 in Server::servePingFlow (this=0xbffff8d4, flow=0xb72005a8) at server.cc:153
#5  0x0804d8ca in operator() (__args#3=<optimized out>, __object=<optimized out>, this=0xb7200654) at /usr/include/c++/4.7/functional:554
#6  _M_invoke<0u, 1u> (this=0xb720064c) at /usr/include/c++/4.7/functional:1598
#7  operator() (this=0xb720064c) at /usr/include/c++/4.7/functional:1586
#8  std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Server::*)(rina::Flow*)> (Server*, rina::Flow*)> >::_M_run() (this=0xb7200640) at /usr/include/c++/4.7/thread:115
#9  0xb7d663c7 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#10  0xb7dd2c39 in start_thread () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
#11  0xb7bea78e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
