### ISSUE TITLE
rinad doesn't compile. Java issue, Major.Minor error. Not present before in previous checkout ( ~ oct 6)

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#98]
<a href="https://github.com/dstaesse"><img src="https://avatars.githubusercontent.com/u/3341175?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dstaesse](https://github.com/dstaesse)**
_Tuesday Oct 15, 2013 at 15:15 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/95_

----

logfile:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by RINA Daemons configure 0.2.2.107-6b8c, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/users/dstaesse/IRATI/buildtree/

## --------- ##

hostname = noded.basiclan.irati.wall1.ilabt.iminds.be
uname -m = x86_64
uname -r = 3.9.6-ilab.t.vlan.transparency
uname -s = Linux
uname -v = #8 SMP Wed Jul 31 01:12:43 CEST 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/testbed/bin
PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /usr/games
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /users/dstaesse/bin

## ----------- ##

configure:1785: checking for a BSD-compatible install
configure:1853: result: /usr/bin/install -c
configure:1864: checking whether build environment is sane
configure:1914: result: yes
configure:2055: checking for a thread-safe mkdir -p
configure:2094: result: /bin/mkdir -p
configure:2107: checking for gawk
configure:2137: result: no
configure:2107: checking for mawk
configure:2123: found /usr/bin/mawk
configure:2134: result: mawk
configure:2145: checking whether make sets $(MAKE)
configure:2167: result: yes
configure:2242: checking how to create a pax tar archive
configure:2255: tar --version
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
configure:2258: $? = 0
configure:2298: tardir=conftest.dir && eval tar --format=posix -chf - "$tardir" >conftest.tar
configure:2301: $? = 0
configure:2305: tar -xf - <conftest.tar
configure:2308: $? = 0
configure:2321: result: gnutar
configure:2330: checking for a sed that does not truncate output
configure:2394: result: /bin/sed
configure:2399: checking for grep that handles long lines and -e
configure:2457: result: /bin/grep
configure:2463: checking whether ln -s works
configure:2467: result: yes
configure:2477: checking for fmt
configure:2495: found /usr/bin/fmt
configure:2508: result: /usr/bin/fmt
configure:2518: checking for sort
configure:2536: found /usr/bin/sort
configure:2549: result: /usr/bin/sort
configure:2559: checking for uniq
configure:2577: found /usr/bin/uniq
configure:2590: result: /usr/bin/uniq
configure:2600: checking for git
configure:2618: found /usr/bin/git
configure:2631: result: /usr/bin/git
configure:2646: checking for kaffe
configure:2676: result: no
configure:2646: checking for java
configure:2662: found /usr/bin/java
configure:2673: result: java
configure:2733: checking for uudecode
configure:2764: result: no
configure:2805: WARNING: I have to compile Test.class from scratch
configure:2817: checking for gcj
configure:2847: result: no
configure:2817: checking for guavac
configure:2847: result: no
configure:2817: checking for jikes
configure:2847: result: no
configure:2817: checking for javac
configure:2833: found /usr/bin/javac
configure:2844: result: javac
configure:2902: checking if javac works
configure:2916: javac  Test.java
configure:2919: $? = 0
configure:2930: result: yes
configure:2936: checking if java works
configure:2954: javac  Test.java
configure:2957: $? = 0
configure:2967: java -classpath .  Test
Exception in thread "main" java.lang.UnsupportedClassVersionError: Test : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: Test. Program will exit.
configure:2970: $? = 1
configure: failed program was:
/* [#]line 2946 "configure" */
public class Test {
public static void main (String args[]) {
        System.exit (0);
} }
configure:2976: error: The Java VM java failed (see config.log, check the CLASSPATH?)

## ---------------- ##

ac_cv_env_LIBRINA_CFLAGS_set=
ac_cv_env_LIBRINA_CFLAGS_value=
ac_cv_env_LIBRINA_LIBS_set=
ac_cv_env_LIBRINA_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=set
ac_cv_env_PKG_CONFIG_PATH_value=/users/dstaesse/IRATI/buildtree//lib/pkgconfig
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_FMT=/usr/bin/fmt
ac_cv_path_GIT=/usr/bin/git
ac_cv_path_GREP=/bin/grep
ac_cv_path_SED=/bin/sed
ac_cv_path_SORT=/usr/bin/sort
ac_cv_path_UNIQ=/usr/bin/uniq
ac_cv_path_UUDECODE=no
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=mawk
ac_cv_prog_JAVA=java
ac_cv_prog_JAVAC=javac
ac_cv_prog_javac_works=yes
ac_cv_prog_make_make_set=yes
am_cv_prog_tar_pax=gnutar

## ----------------- ##

ACLOCAL='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/missing --run aclocal-1.11'
AMTAR='$${TAR-tar}'
AUTOCONF='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/missing --run autoconf'
AUTOHEADER='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/missing --run autoheader'
AUTOMAKE='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/missing --run automake-1.11'
AWK='mawk'
CYGPATH_W='echo'
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
FMT='/usr/bin/fmt'
GIT='/usr/bin/git'
GREP='/bin/grep'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
JAVA='java'
JAVAC='javac'
LIBOBJS=''
LIBRINA_CFLAGS=''
LIBRINA_LIBS=''
LIBRINA_VERSION=''
LIBS=''
LN_S='ln -s'
LTLIBOBJS=''
MAKEINFO='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/missing --run makeinfo'
MKDIR_P='/bin/mkdir -p'
MVN=''
PACKAGE='rinad'
PACKAGE_BUGREPORT='f.salvestrini@nextworks.it'
PACKAGE_NAME='RINA Daemons'
PACKAGE_STRING='RINA Daemons 0.2.2.107-6b8c'
PACKAGE_TARNAME='rinad'
PACKAGE_URL='http://irati.eu'
PACKAGE_VERSION='0.2.2.107-6b8c'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH='/users/dstaesse/IRATI/buildtree//lib/pkgconfig'
SED='/bin/sed'
SET_MAKE=''
SHELL='/bin/bash'
SORT='/usr/bin/sort'
STRIP=''
UNIQ='/usr/bin/uniq'
UUDECODE='no'
VERSION='0.2.2.107-6b8c'
am__isrc=''
am__leading_dot='.'
am__tar='tar --format=posix -chf - "$$tardir"'
am__untar='tar -xf -'
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /users/dstaesse/IRATI/irati/rinad/build-aux/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/users/dstaesse/IRATI/buildtree'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "RINA Daemons"
#define PACKAGE_TARNAME "rinad"
#define PACKAGE_VERSION "0.2.2.107-6b8c"
#define PACKAGE_STRING "RINA Daemons 0.2.2.107-6b8c"
#define PACKAGE_BUGREPORT "f.salvestrini@nextworks.it"
#define PACKAGE_URL "http://irati.eu"
#define PACKAGE "rinad"
#define VERSION "0.2.2.107-6b8c"

configure: exit 1

**Comment by kewinrausch** [comment]
<a href="https://github.com/dstaesse"><img src="https://avatars.githubusercontent.com/u/3341175?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dstaesse](https://github.com/dstaesse)**
_Tuesday Oct 15, 2013 at 20:24 GMT_

----

Issue solved by removing / reinstalling everything remotely java-related. New image snapshot for vwall created.
Eduard to add jdk/jre version checks in the configuration/build scripts (as per request of Francesco).

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Thursday Oct 17, 2013 at 07:07 GMT_

----

This was due to the fact that Java 7 was used to compile (without compatibility for Java6 support) and Java 6 was used to run.

**Comment by kewinrausch** [comment]
<a href="https://github.com/salvestrini"><img src="https://avatars.githubusercontent.com/u/81804?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salvestrini](https://github.com/salvestrini)**
_Thursday Oct 17, 2013 at 09:41 GMT_

----

We could add checks here and there to avoid such conditions, if we know how
to detect them... Might you help me find the proper checks ?

However, let's find to solve this during MS7.x (x >= 1)
